# Generated by Django 5.1.5 on 2025-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='prev_img',
            field=models.ImageField(default='True', upload_to='prev_img/banners/'),
        ),
        migrations.AddField(
            model_name='banneronthemainpage',
            name='prev_img',
            field=models.ImageField(default='True', upload_to='prev_img/banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='series',
            name='prev_img',
            field=models.ImageField(default='True', upload_to='prev_img/'),
        ),
        migrations.AddField(
            model_name='voiceactor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='VoiceActors/'),
        ),
    ]
