# Generated by Django 5.1.5 on 2025-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubka', '0002_banner_prev_img_banneronthemainpage_prev_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceactor',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
